### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Nick-Howlett** [Nick-Howlett/Sherwood#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
Collapse

Today

**Comment by jenkennedy** [comment]
- [ ] robinhood logo (the word) should be black.  Currently has color styling of a link (blue - turns dark blue after clicked)
- [ ] Header items have too small of font weight
- [ ] "Invest for free" has too small of font weight
- [ ] Add a bit more space between the Sign Up and Demo Login buttons
+ Bonus: add a demo login button to both the log in and sign up pages
- [ ] Login and signup page image takes up too much of the page.  Should be 50%

**Comment by jenkennedy** [comment]
- [ ] reduce font weight of robinhood logo (the word) to match robinhood.com

**Comment by jenkennedy** [comment]
Great job!
