### ISSUE TITLE
PA Review: Stock Detail Page

### ISSUE THREAD

**Issue by Nick-Howlett** [Nick-Howlett/Sherwood#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Users can visit /stocks/:symbol for any stock traded by the IEX
- [x] Users can view 1d-5y charts for a stock's performance
- [x] Stock charts are interactive, and display appropriate values on mouseover
- [x] Stock page displays detailed statistics and a description of the company
- [x] Stock shows related news
- [x] Description, statistics, and news have buttons to show/read more
- [x] Users can buy and sell stocks if logged in
- [x] Users cannot buy or sell stocks if they don't have the appropriate buying power/number of stocks
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
It's looking so great! Just a couple things:
- [ ] Redirect "Sign Up to Buy" to your Sign Up page
- [ ] Remove logger

**Comment by jenkennedy** [comment]
- [ ] Fix this stock detail: 
![screen shot 2019-03-06 at 11 00 24 am](https://user-images.githubusercontent.com/39272166/53906232-3fbbe680-3fff-11e9-9459-7b8aeef11a0c.png)

**Comment by Nick-Howlett** [comment]
For some charts I'm able to close the gaps in data, but for others like reality shares NASDAQ Nexgen etc I can't do much about it. Should I display something like "insufficient data for 1d chart"?
