### ISSUE TITLE
PA Review: Stock Search

### ISSUE THREAD

**Issue by Nick-Howlett** [Nick-Howlett/Sherwood#4]
- [x] Presentational Components and Containers
- [x] Searchbar added to navbar, appears on user profile and stock detail page but not splash page.
- [x] Searchbar 'pops out' on hover, opens when results are typed
- [x] Search results are displayed over the top of the page details on user scroll
- [x] Search results close when user clicks outside
- [x] Search shows appropriate results for query string, searches by both company and symbol.
- [x] Search results are links to stock detail pages
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
Awesome job! 

- BONUS: Allow keystrokes to control selecting an item from the dropdown
